echo off
SET CHROMEBASE=%LOCALAPPDATA%\Google\Chrome\User Data\Default\Bookmarks

SET COMPLETE=%HOMEPATH%\Desktop\Lab_Files\Bookmarks\DONE.TXT
SET CHROMEBACKUPDIR=%HOMEPATH%\Desktop\Lab_Files\Bookmarks

IF %COMPUTERNAME% == SID-SEC1 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks1" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC2 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks2" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC3 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks3" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC4 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks4" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC5 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks5" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC6 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks6" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC7 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks7" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC8 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks8" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC9 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks9" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC10 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks10" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC11 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks11" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC12 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks12" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC13 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks13" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC14 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks14" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC15 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks15" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC16 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks16" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC17 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks17" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC18 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks18" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC19 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks19" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC20 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks20" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC21 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks21" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC22 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks22" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC23 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks23" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC24 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks24" "%CHROMEBASE%"
IF %COMPUTERNAME% == SID-SEC25 IF EXIST "%CHROMEBACKUPDIR%" COPY /Y "%CHROMEBACKUPDIR%\Bookmarks25" "%CHROMEBASE%"
echo "COMPETE" > %COMPLETE%

